//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operador", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Operador : object
    {
        
        private bool getSetAdminField;
        
        private bool getSetCadastroCategoriaField;
        
        private bool getSetCadastroClienteField;
        
        private bool getSetCadastroFormaPGTOField;
        
        private bool getSetCadastroOperadorField;
        
        private bool getSetCadastroProdutoField;
        
        private bool getSetEntradaField;
        
        private int getSetIDField;
        
        private string getSetNomeField;
        
        private bool getSetPedidosField;
        
        private string getSetSenhaField;
        
        private bool getSetStatusField;
        
        private bool getSetTabelaUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetAdmin
        {
            get
            {
                return this.getSetAdminField;
            }
            set
            {
                this.getSetAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetCadastroCategoria
        {
            get
            {
                return this.getSetCadastroCategoriaField;
            }
            set
            {
                this.getSetCadastroCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetCadastroCliente
        {
            get
            {
                return this.getSetCadastroClienteField;
            }
            set
            {
                this.getSetCadastroClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetCadastroFormaPGTO
        {
            get
            {
                return this.getSetCadastroFormaPGTOField;
            }
            set
            {
                this.getSetCadastroFormaPGTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetCadastroOperador
        {
            get
            {
                return this.getSetCadastroOperadorField;
            }
            set
            {
                this.getSetCadastroOperadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetCadastroProduto
        {
            get
            {
                return this.getSetCadastroProdutoField;
            }
            set
            {
                this.getSetCadastroProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetEntrada
        {
            get
            {
                return this.getSetEntradaField;
            }
            set
            {
                this.getSetEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetPedidos
        {
            get
            {
                return this.getSetPedidosField;
            }
            set
            {
                this.getSetPedidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetSenha
        {
            get
            {
                return this.getSetSenhaField;
            }
            set
            {
                this.getSetSenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetTabelaUsuario
        {
            get
            {
                return this.getSetTabelaUsuarioField;
            }
            set
            {
                this.getSetTabelaUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Cliente : object
    {
        
        private string getSetBairroField;
        
        private string getSetCEPField;
        
        private string getSetCPFField;
        
        private string getSetCidadeField;
        
        private string getSetDtNascimentoField;
        
        private string getSetEmailField;
        
        private string getSetEnderecoField;
        
        private string getSetEstadoField;
        
        private int getSetIDField;
        
        private int getSetMoradiaField;
        
        private string getSetNomeField;
        
        private string getSetNumeroField;
        
        private bool getSetStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetBairro
        {
            get
            {
                return this.getSetBairroField;
            }
            set
            {
                this.getSetBairroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetCEP
        {
            get
            {
                return this.getSetCEPField;
            }
            set
            {
                this.getSetCEPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetCPF
        {
            get
            {
                return this.getSetCPFField;
            }
            set
            {
                this.getSetCPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetCidade
        {
            get
            {
                return this.getSetCidadeField;
            }
            set
            {
                this.getSetCidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetDtNascimento
        {
            get
            {
                return this.getSetDtNascimentoField;
            }
            set
            {
                this.getSetDtNascimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetEmail
        {
            get
            {
                return this.getSetEmailField;
            }
            set
            {
                this.getSetEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetEndereco
        {
            get
            {
                return this.getSetEnderecoField;
            }
            set
            {
                this.getSetEnderecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetEstado
        {
            get
            {
                return this.getSetEstadoField;
            }
            set
            {
                this.getSetEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetMoradia
        {
            get
            {
                return this.getSetMoradiaField;
            }
            set
            {
                this.getSetMoradiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNumero
        {
            get
            {
                return this.getSetNumeroField;
            }
            set
            {
                this.getSetNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoClientes", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class TipoClientes : object
    {
        
        private bool getSetTipoClienteField;
        
        private bool getSetTipoFornecedorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetTipoCliente
        {
            get
            {
                return this.getSetTipoClienteField;
            }
            set
            {
                this.getSetTipoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetTipoFornecedor
        {
            get
            {
                return this.getSetTipoFornecedorField;
            }
            set
            {
                this.getSetTipoFornecedorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfiguracoesGerais", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class ConfiguracoesGerais : object
    {
        
        private bool getSetAlterarValorItemField;
        
        private double getSetMaxDescontoItensPedidoField;
        
        private double getSetMaxDescontoPedidoField;
        
        private bool getSetVendaItemNegativoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetAlterarValorItem
        {
            get
            {
                return this.getSetAlterarValorItemField;
            }
            set
            {
                this.getSetAlterarValorItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetMaxDescontoItensPedido
        {
            get
            {
                return this.getSetMaxDescontoItensPedidoField;
            }
            set
            {
                this.getSetMaxDescontoItensPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetMaxDescontoPedido
        {
            get
            {
                return this.getSetMaxDescontoPedidoField;
            }
            set
            {
                this.getSetMaxDescontoPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetVendaItemNegativo
        {
            get
            {
                return this.getSetVendaItemNegativoField;
            }
            set
            {
                this.getSetVendaItemNegativoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Produto : object
    {
        
        private int getSetCategoriaField;
        
        private double getSetCustoField;
        
        private int getSetIDField;
        
        private string getSetNomeField;
        
        private bool getSetStatusField;
        
        private double getSetValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetCategoria
        {
            get
            {
                return this.getSetCategoriaField;
            }
            set
            {
                this.getSetCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCusto
        {
            get
            {
                return this.getSetCustoField;
            }
            set
            {
                this.getSetCustoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValor
        {
            get
            {
                return this.getSetValorField;
            }
            set
            {
                this.getSetValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estados", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Estados : object
    {
        
        private int getSetIDField;
        
        private string getSetNomeField;
        
        private string getSetUFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetUF
        {
            get
            {
                return this.getSetUFField;
            }
            set
            {
                this.getSetUFField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaPGTO", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class FormaPGTO : object
    {
        
        private int getSetIDField;
        
        private string getSetNomeField;
        
        private bool getSetStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Categoria : object
    {
        
        private int getSetIDField;
        
        private string getSetNomeField;
        
        private bool getSetStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Pedido : object
    {
        
        private int getSetClienteField;
        
        private string getSetDataField;
        
        private double getSetDescontoField;
        
        private int getSetFormaPGTOField;
        
        private int getSetIDField;
        
        private double getSetValorField;
        
        private double getSetValorTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetCliente
        {
            get
            {
                return this.getSetClienteField;
            }
            set
            {
                this.getSetClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetData
        {
            get
            {
                return this.getSetDataField;
            }
            set
            {
                this.getSetDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetDesconto
        {
            get
            {
                return this.getSetDescontoField;
            }
            set
            {
                this.getSetDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetFormaPGTO
        {
            get
            {
                return this.getSetFormaPGTOField;
            }
            set
            {
                this.getSetFormaPGTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValor
        {
            get
            {
                return this.getSetValorField;
            }
            set
            {
                this.getSetValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValorTotal
        {
            get
            {
                return this.getSetValorTotalField;
            }
            set
            {
                this.getSetValorTotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoItens", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class PedidoItens : object
    {
        
        private double getSetItemDescontoField;
        
        private int getSetItemIDField;
        
        private string getSetItemNomeProdutoField;
        
        private double getSetItemValorField;
        
        private double getSetItemValorTotalField;
        
        private int getSetPedidoIDField;
        
        private int getSetProdutoField;
        
        private int getSetQuantidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetItemDesconto
        {
            get
            {
                return this.getSetItemDescontoField;
            }
            set
            {
                this.getSetItemDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetItemID
        {
            get
            {
                return this.getSetItemIDField;
            }
            set
            {
                this.getSetItemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetItemNomeProduto
        {
            get
            {
                return this.getSetItemNomeProdutoField;
            }
            set
            {
                this.getSetItemNomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetItemValor
        {
            get
            {
                return this.getSetItemValorField;
            }
            set
            {
                this.getSetItemValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetItemValorTotal
        {
            get
            {
                return this.getSetItemValorTotalField;
            }
            set
            {
                this.getSetItemValorTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetPedidoID
        {
            get
            {
                return this.getSetPedidoIDField;
            }
            set
            {
                this.getSetPedidoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetProduto
        {
            get
            {
                return this.getSetProdutoField;
            }
            set
            {
                this.getSetProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetQuantidade
        {
            get
            {
                return this.getSetQuantidadeField;
            }
            set
            {
                this.getSetQuantidadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoComDados", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class PedidoComDados : object
    {
        
        private string getSetClienteField;
        
        private string getSetDataField;
        
        private double getSetDescontoField;
        
        private string getSetFormaPGTOField;
        
        private int getSetIDField;
        
        private double getSetValorField;
        
        private double getSetValorTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetCliente
        {
            get
            {
                return this.getSetClienteField;
            }
            set
            {
                this.getSetClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetData
        {
            get
            {
                return this.getSetDataField;
            }
            set
            {
                this.getSetDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetDesconto
        {
            get
            {
                return this.getSetDescontoField;
            }
            set
            {
                this.getSetDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetFormaPGTO
        {
            get
            {
                return this.getSetFormaPGTOField;
            }
            set
            {
                this.getSetFormaPGTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValor
        {
            get
            {
                return this.getSetValorField;
            }
            set
            {
                this.getSetValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValorTotal
        {
            get
            {
                return this.getSetValorTotalField;
            }
            set
            {
                this.getSetValorTotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class Entrada : object
    {
        
        private int getSetClienteField;
        
        private double getSetCustoField;
        
        private double getSetCustoTotalField;
        
        private string getSetDataField;
        
        private double getSetDescontoField;
        
        private int getSetFormaPGTOField;
        
        private int getSetIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetCliente
        {
            get
            {
                return this.getSetClienteField;
            }
            set
            {
                this.getSetClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCusto
        {
            get
            {
                return this.getSetCustoField;
            }
            set
            {
                this.getSetCustoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCustoTotal
        {
            get
            {
                return this.getSetCustoTotalField;
            }
            set
            {
                this.getSetCustoTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetData
        {
            get
            {
                return this.getSetDataField;
            }
            set
            {
                this.getSetDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetDesconto
        {
            get
            {
                return this.getSetDescontoField;
            }
            set
            {
                this.getSetDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetFormaPGTO
        {
            get
            {
                return this.getSetFormaPGTOField;
            }
            set
            {
                this.getSetFormaPGTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaItens", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class EntradaItens : object
    {
        
        private int getSetEntradaIDField;
        
        private double getSetItemCustoField;
        
        private double getSetItemCustoTotalField;
        
        private double getSetItemDescontoField;
        
        private int getSetItemIDField;
        
        private string getSetItemNomeProdutoField;
        
        private int getSetProdutoField;
        
        private int getSetQuantidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetEntradaID
        {
            get
            {
                return this.getSetEntradaIDField;
            }
            set
            {
                this.getSetEntradaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetItemCusto
        {
            get
            {
                return this.getSetItemCustoField;
            }
            set
            {
                this.getSetItemCustoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetItemCustoTotal
        {
            get
            {
                return this.getSetItemCustoTotalField;
            }
            set
            {
                this.getSetItemCustoTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetItemDesconto
        {
            get
            {
                return this.getSetItemDescontoField;
            }
            set
            {
                this.getSetItemDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetItemID
        {
            get
            {
                return this.getSetItemIDField;
            }
            set
            {
                this.getSetItemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetItemNomeProduto
        {
            get
            {
                return this.getSetItemNomeProdutoField;
            }
            set
            {
                this.getSetItemNomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetProduto
        {
            get
            {
                return this.getSetProdutoField;
            }
            set
            {
                this.getSetProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetQuantidade
        {
            get
            {
                return this.getSetQuantidadeField;
            }
            set
            {
                this.getSetQuantidadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaComDados", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class EntradaComDados : object
    {
        
        private string getSetClienteField;
        
        private double getSetCustoField;
        
        private double getSetCustoTotalField;
        
        private string getSetDataField;
        
        private double getSetDescontoField;
        
        private string getSetFormaPGTOField;
        
        private int getSetIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetCliente
        {
            get
            {
                return this.getSetClienteField;
            }
            set
            {
                this.getSetClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCusto
        {
            get
            {
                return this.getSetCustoField;
            }
            set
            {
                this.getSetCustoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCustoTotal
        {
            get
            {
                return this.getSetCustoTotalField;
            }
            set
            {
                this.getSetCustoTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetData
        {
            get
            {
                return this.getSetDataField;
            }
            set
            {
                this.getSetDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetDesconto
        {
            get
            {
                return this.getSetDescontoField;
            }
            set
            {
                this.getSetDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetFormaPGTO
        {
            get
            {
                return this.getSetFormaPGTOField;
            }
            set
            {
                this.getSetFormaPGTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaPedido", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class ListaPedido : object
    {
        
        private int getSetCodigoField;
        
        private string getSetDataField;
        
        private double getSetValorField;
        
        private string getSetclienteField;
        
        private string getSetformaPGTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetCodigo
        {
            get
            {
                return this.getSetCodigoField;
            }
            set
            {
                this.getSetCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetData
        {
            get
            {
                return this.getSetDataField;
            }
            set
            {
                this.getSetDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValor
        {
            get
            {
                return this.getSetValorField;
            }
            set
            {
                this.getSetValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetcliente
        {
            get
            {
                return this.getSetclienteField;
            }
            set
            {
                this.getSetclienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetformaPGTO
        {
            get
            {
                return this.getSetformaPGTOField;
            }
            set
            {
                this.getSetformaPGTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaCliente", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class ListaCliente : object
    {
        
        private int getSetCodigoField;
        
        private string getSetDocumentoField;
        
        private string getSetDtNascField;
        
        private string getSetNomeField;
        
        private bool getSetStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetCodigo
        {
            get
            {
                return this.getSetCodigoField;
            }
            set
            {
                this.getSetCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetDocumento
        {
            get
            {
                return this.getSetDocumentoField;
            }
            set
            {
                this.getSetDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetDtNasc
        {
            get
            {
                return this.getSetDtNascField;
            }
            set
            {
                this.getSetDtNascField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaProduto", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class ListaProduto : object
    {
        
        private string getSetCategoriaField;
        
        private double getSetCustoField;
        
        private long getSetEstoqueField;
        
        private int getSetIDField;
        
        private string getSetNomeField;
        
        private bool getSetStatusField;
        
        private double getSetValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetCategoria
        {
            get
            {
                return this.getSetCategoriaField;
            }
            set
            {
                this.getSetCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCusto
        {
            get
            {
                return this.getSetCustoField;
            }
            set
            {
                this.getSetCustoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long getSetEstoque
        {
            get
            {
                return this.getSetEstoqueField;
            }
            set
            {
                this.getSetEstoqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetNome
        {
            get
            {
                return this.getSetNomeField;
            }
            set
            {
                this.getSetNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getSetStatus
        {
            get
            {
                return this.getSetStatusField;
            }
            set
            {
                this.getSetStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetValor
        {
            get
            {
                return this.getSetValorField;
            }
            set
            {
                this.getSetValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaEntrada", Namespace="http://schemas.datacontract.org/2004/07/WEBServiceWCF.Classes")]
    public partial class ListaEntrada : object
    {
        
        private double getSetCustoField;
        
        private string getSetDataField;
        
        private string getSetFornecedorField;
        
        private int getSetIDField;
        
        private string getSetformaPGTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double getSetCusto
        {
            get
            {
                return this.getSetCustoField;
            }
            set
            {
                this.getSetCustoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetData
        {
            get
            {
                return this.getSetDataField;
            }
            set
            {
                this.getSetDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetFornecedor
        {
            get
            {
                return this.getSetFornecedorField;
            }
            set
            {
                this.getSetFornecedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getSetID
        {
            get
            {
                return this.getSetIDField;
            }
            set
            {
                this.getSetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getSetformaPGTO
        {
            get
            {
                return this.getSetformaPGTOField;
            }
            set
            {
                this.getSetformaPGTOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOperador", ReplyAction="http://tempuri.org/IService1/GetOperadorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Operador> GetOperadorAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificaOperador", ReplyAction="http://tempuri.org/IService1/VerificaOperadorResponse")]
        System.Threading.Tasks.Task<int> VerificaOperadorAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificaLogin", ReplyAction="http://tempuri.org/IService1/VerificaLoginResponse")]
        System.Threading.Tasks.Task<int> VerificaLoginAsync(int ID, int senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegistroInicialOperador", ReplyAction="http://tempuri.org/IService1/GetRegistroInicialOperadorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Operador> GetRegistroInicialOperadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroOperador", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroOperadorResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroOperadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroOperador", ReplyAction="http://tempuri.org/IService1/AvancarRegistroOperadorResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroOperadorAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroOperador", ReplyAction="http://tempuri.org/IService1/VoltarRegistroOperadorResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroOperadorAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SalvarOperador", ReplyAction="http://tempuri.org/IService1/SalvarOperadorResponse")]
        System.Threading.Tasks.Task<int> SalvarOperadorAsync(ServiceReference1.Operador operador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCliente", ReplyAction="http://tempuri.org/IService1/GetClienteResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cliente> GetClienteAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClienteInicial", ReplyAction="http://tempuri.org/IService1/GetClienteInicialResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cliente> GetClienteInicialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroCliente", ReplyAction="http://tempuri.org/IService1/AvancarRegistroClienteResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroClienteAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroCliente", ReplyAction="http://tempuri.org/IService1/VoltarRegistroClienteResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroClienteAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SalvarCliente", ReplyAction="http://tempuri.org/IService1/SalvarClienteResponse")]
        System.Threading.Tasks.Task<int> SalvarClienteAsync(ServiceReference1.Cliente cliente, ServiceReference1.TipoClientes tipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroCliente", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroClienteResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipoClientes", ReplyAction="http://tempuri.org/IService1/GetTipoClientesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TipoClientes> GetTipoClientesAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDadosConfiguracoesGerais", ReplyAction="http://tempuri.org/IService1/GetDadosConfiguracoesGeraisResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ConfiguracoesGerais> GetDadosConfiguracoesGeraisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SalvarConfiguracoesGerais", ReplyAction="http://tempuri.org/IService1/SalvarConfiguracoesGeraisResponse")]
        System.Threading.Tasks.Task<int> SalvarConfiguracoesGeraisAsync(ServiceReference1.ConfiguracoesGerais config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduto", ReplyAction="http://tempuri.org/IService1/GetProdutoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Produto> GetProdutoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdutoInicial", ReplyAction="http://tempuri.org/IService1/GetProdutoInicialResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Produto> GetProdutoInicialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroProduto", ReplyAction="http://tempuri.org/IService1/AvancarRegistroProdutoResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroProdutoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroProduto", ReplyAction="http://tempuri.org/IService1/VoltarRegistroProdutoResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroProdutoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEstoqueProduto", ReplyAction="http://tempuri.org/IService1/GetEstoqueProdutoResponse")]
        System.Threading.Tasks.Task<int> GetEstoqueProdutoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SalvarProduto", ReplyAction="http://tempuri.org/IService1/SalvarProdutoResponse")]
        System.Threading.Tasks.Task<int> SalvarProdutoAsync(ServiceReference1.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroProduto", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroProdutoResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroProdutoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListEstados", ReplyAction="http://tempuri.org/IService1/GetListEstadosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Estados[]> GetListEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFormaPGTO", ReplyAction="http://tempuri.org/IService1/GetFormaPGTOResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FormaPGTO> GetFormaPGTOAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegistroInicialFormaPGTO", ReplyAction="http://tempuri.org/IService1/GetRegistroInicialFormaPGTOResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FormaPGTO> GetRegistroInicialFormaPGTOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroFormaPGTO", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroFormaPGTOResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroFormaPGTOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroFormaPGTO", ReplyAction="http://tempuri.org/IService1/AvancarRegistroFormaPGTOResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroFormaPGTOAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroFormaPGTO", ReplyAction="http://tempuri.org/IService1/VoltarRegistroFormaPGTOResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroFormaPGTOAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarNomeFormaPGTO", ReplyAction="http://tempuri.org/IService1/ValidarNomeFormaPGTOResponse")]
        System.Threading.Tasks.Task<int> ValidarNomeFormaPGTOAsync(ServiceReference1.FormaPGTO formaPGTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SalvarFormaPGTO", ReplyAction="http://tempuri.org/IService1/SalvarFormaPGTOResponse")]
        System.Threading.Tasks.Task<int> SalvarFormaPGTOAsync(ServiceReference1.FormaPGTO formaPGTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoria", ReplyAction="http://tempuri.org/IService1/GetCategoriaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Categoria> GetCategoriaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegistroInicialCategoria", ReplyAction="http://tempuri.org/IService1/GetRegistroInicialCategoriaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Categoria> GetRegistroInicialCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroCategoria", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroCategoriaResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroCategoria", ReplyAction="http://tempuri.org/IService1/AvancarRegistroCategoriaResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroCategoriaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroCategoria", ReplyAction="http://tempuri.org/IService1/VoltarRegistroCategoriaResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroCategoriaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarNomeCategoria", ReplyAction="http://tempuri.org/IService1/ValidarNomeCategoriaResponse")]
        System.Threading.Tasks.Task<int> ValidarNomeCategoriaAsync(ServiceReference1.Categoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SalvarCategoria", ReplyAction="http://tempuri.org/IService1/SalvarCategoriaResponse")]
        System.Threading.Tasks.Task<int> SalvarCategoriaAsync(ServiceReference1.Categoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCategorias", ReplyAction="http://tempuri.org/IService1/GetAllCategoriasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Categoria[]> GetAllCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPedido", ReplyAction="http://tempuri.org/IService1/GetPedidoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Pedido> GetPedidoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPedidoItens", ReplyAction="http://tempuri.org/IService1/GetPedidoItensResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PedidoItens[]> GetPedidoItensAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegistroInicialPedido", ReplyAction="http://tempuri.org/IService1/GetRegistroInicialPedidoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Pedido> GetRegistroInicialPedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPedidoComDados", ReplyAction="http://tempuri.org/IService1/GetPedidoComDadosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PedidoComDados> GetPedidoComDadosAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroPedido", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroPedidoResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroPedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroPedido", ReplyAction="http://tempuri.org/IService1/AvancarRegistroPedidoResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroPedidoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroPedido", ReplyAction="http://tempuri.org/IService1/VoltarRegistroPedidoResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroPedidoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/salvarItensPedido", ReplyAction="http://tempuri.org/IService1/salvarItensPedidoResponse")]
        System.Threading.Tasks.Task salvarItensPedidoAsync(ServiceReference1.PedidoItens item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/excluirItemPedido", ReplyAction="http://tempuri.org/IService1/excluirItemPedidoResponse")]
        System.Threading.Tasks.Task excluirItemPedidoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/excluirItensPedido", ReplyAction="http://tempuri.org/IService1/excluirItensPedidoResponse")]
        System.Threading.Tasks.Task excluirItensPedidoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarValorPedido", ReplyAction="http://tempuri.org/IService1/VerificarValorPedidoResponse")]
        System.Threading.Tasks.Task<double> VerificarValorPedidoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FinalizarPedido", ReplyAction="http://tempuri.org/IService1/FinalizarPedidoResponse")]
        System.Threading.Tasks.Task<int> FinalizarPedidoAsync(ServiceReference1.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntrada", ReplyAction="http://tempuri.org/IService1/GetEntradaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Entrada> GetEntradaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntradaItens", ReplyAction="http://tempuri.org/IService1/GetEntradaItensResponse")]
        System.Threading.Tasks.Task<ServiceReference1.EntradaItens[]> GetEntradaItensAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegistroInicialEntrada", ReplyAction="http://tempuri.org/IService1/GetRegistroInicialEntradaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Entrada> GetRegistroInicialEntradaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntradaComDados", ReplyAction="http://tempuri.org/IService1/GetEntradaComDadosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.EntradaComDados> GetEntradaComDadosAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProximoRegistroEntrada", ReplyAction="http://tempuri.org/IService1/GetProximoRegistroEntradaResponse")]
        System.Threading.Tasks.Task<int> GetProximoRegistroEntradaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AvancarRegistroEntrada", ReplyAction="http://tempuri.org/IService1/AvancarRegistroEntradaResponse")]
        System.Threading.Tasks.Task<int> AvancarRegistroEntradaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VoltarRegistroEntrada", ReplyAction="http://tempuri.org/IService1/VoltarRegistroEntradaResponse")]
        System.Threading.Tasks.Task<int> VoltarRegistroEntradaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/salvarItensEntrada", ReplyAction="http://tempuri.org/IService1/salvarItensEntradaResponse")]
        System.Threading.Tasks.Task salvarItensEntradaAsync(ServiceReference1.EntradaItens item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/excluirItemEntrada", ReplyAction="http://tempuri.org/IService1/excluirItemEntradaResponse")]
        System.Threading.Tasks.Task excluirItemEntradaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/excluirItensEntrada", ReplyAction="http://tempuri.org/IService1/excluirItensEntradaResponse")]
        System.Threading.Tasks.Task excluirItensEntradaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarValorEntrada", ReplyAction="http://tempuri.org/IService1/VerificarValorEntradaResponse")]
        System.Threading.Tasks.Task<double> VerificarValorEntradaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FinalizarEntrada", ReplyAction="http://tempuri.org/IService1/FinalizarEntradaResponse")]
        System.Threading.Tasks.Task<int> FinalizarEntradaAsync(ServiceReference1.Entrada entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaPedidos", ReplyAction="http://tempuri.org/IService1/GetListaPedidosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ListaPedido[]> GetListaPedidosAsync(string tipoPesquisa, string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaClientes", ReplyAction="http://tempuri.org/IService1/GetListaClientesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ListaCliente[]> GetListaClientesAsync(string tipoPesquisa, string pesquisa, bool inativo, string tipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaFormaPGTO", ReplyAction="http://tempuri.org/IService1/GetListaFormaPGTOResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FormaPGTO[]> GetListaFormaPGTOAsync(string tipoPesquisa, string pesquisa, bool inativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaProdutos", ReplyAction="http://tempuri.org/IService1/GetListaProdutosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ListaProduto[]> GetListaProdutosAsync(string tipoPesquisa, string pesquisa, bool inativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaCategorias", ReplyAction="http://tempuri.org/IService1/GetListaCategoriasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Categoria[]> GetListaCategoriasAsync(string tipoPesquisa, string pesquisa, bool inativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaOperador", ReplyAction="http://tempuri.org/IService1/GetListaOperadorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Operador[]> GetListaOperadorAsync(string tipoPesquisa, string pesquisa, bool inativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListaEntradas", ReplyAction="http://tempuri.org/IService1/GetListaEntradasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ListaEntrada[]> GetListaEntradasAsync(string tipoPesquisa, string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRelatorioPedido", ReplyAction="http://tempuri.org/IService1/GetRelatorioPedidoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PedidoComDados[]> GetRelatorioPedidoAsync(string dtInicio, string dtFinal, string cliente, string PGTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Operador> GetOperadorAsync(int ID)
        {
            return base.Channel.GetOperadorAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VerificaOperadorAsync(int ID)
        {
            return base.Channel.VerificaOperadorAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VerificaLoginAsync(int ID, int senha)
        {
            return base.Channel.VerificaLoginAsync(ID, senha);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Operador> GetRegistroInicialOperadorAsync()
        {
            return base.Channel.GetRegistroInicialOperadorAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroOperadorAsync()
        {
            return base.Channel.GetProximoRegistroOperadorAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroOperadorAsync(int ID)
        {
            return base.Channel.AvancarRegistroOperadorAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroOperadorAsync(int ID)
        {
            return base.Channel.VoltarRegistroOperadorAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> SalvarOperadorAsync(ServiceReference1.Operador operador)
        {
            return base.Channel.SalvarOperadorAsync(operador);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cliente> GetClienteAsync(int ID)
        {
            return base.Channel.GetClienteAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cliente> GetClienteInicialAsync()
        {
            return base.Channel.GetClienteInicialAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroClienteAsync(int ID)
        {
            return base.Channel.AvancarRegistroClienteAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroClienteAsync(int ID)
        {
            return base.Channel.VoltarRegistroClienteAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> SalvarClienteAsync(ServiceReference1.Cliente cliente, ServiceReference1.TipoClientes tipoCliente)
        {
            return base.Channel.SalvarClienteAsync(cliente, tipoCliente);
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroClienteAsync()
        {
            return base.Channel.GetProximoRegistroClienteAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TipoClientes> GetTipoClientesAsync(int ID)
        {
            return base.Channel.GetTipoClientesAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ConfiguracoesGerais> GetDadosConfiguracoesGeraisAsync()
        {
            return base.Channel.GetDadosConfiguracoesGeraisAsync();
        }
        
        public System.Threading.Tasks.Task<int> SalvarConfiguracoesGeraisAsync(ServiceReference1.ConfiguracoesGerais config)
        {
            return base.Channel.SalvarConfiguracoesGeraisAsync(config);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Produto> GetProdutoAsync(int id)
        {
            return base.Channel.GetProdutoAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Produto> GetProdutoInicialAsync()
        {
            return base.Channel.GetProdutoInicialAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroProdutoAsync(int ID)
        {
            return base.Channel.AvancarRegistroProdutoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroProdutoAsync(int ID)
        {
            return base.Channel.VoltarRegistroProdutoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> GetEstoqueProdutoAsync(int ID)
        {
            return base.Channel.GetEstoqueProdutoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> SalvarProdutoAsync(ServiceReference1.Produto produto)
        {
            return base.Channel.SalvarProdutoAsync(produto);
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroProdutoAsync()
        {
            return base.Channel.GetProximoRegistroProdutoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Estados[]> GetListEstadosAsync()
        {
            return base.Channel.GetListEstadosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FormaPGTO> GetFormaPGTOAsync(int ID)
        {
            return base.Channel.GetFormaPGTOAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FormaPGTO> GetRegistroInicialFormaPGTOAsync()
        {
            return base.Channel.GetRegistroInicialFormaPGTOAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroFormaPGTOAsync()
        {
            return base.Channel.GetProximoRegistroFormaPGTOAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroFormaPGTOAsync(int ID)
        {
            return base.Channel.AvancarRegistroFormaPGTOAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroFormaPGTOAsync(int ID)
        {
            return base.Channel.VoltarRegistroFormaPGTOAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> ValidarNomeFormaPGTOAsync(ServiceReference1.FormaPGTO formaPGTO)
        {
            return base.Channel.ValidarNomeFormaPGTOAsync(formaPGTO);
        }
        
        public System.Threading.Tasks.Task<int> SalvarFormaPGTOAsync(ServiceReference1.FormaPGTO formaPGTO)
        {
            return base.Channel.SalvarFormaPGTOAsync(formaPGTO);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Categoria> GetCategoriaAsync(int ID)
        {
            return base.Channel.GetCategoriaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Categoria> GetRegistroInicialCategoriaAsync()
        {
            return base.Channel.GetRegistroInicialCategoriaAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroCategoriaAsync()
        {
            return base.Channel.GetProximoRegistroCategoriaAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroCategoriaAsync(int ID)
        {
            return base.Channel.AvancarRegistroCategoriaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroCategoriaAsync(int ID)
        {
            return base.Channel.VoltarRegistroCategoriaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> ValidarNomeCategoriaAsync(ServiceReference1.Categoria categoria)
        {
            return base.Channel.ValidarNomeCategoriaAsync(categoria);
        }
        
        public System.Threading.Tasks.Task<int> SalvarCategoriaAsync(ServiceReference1.Categoria categoria)
        {
            return base.Channel.SalvarCategoriaAsync(categoria);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Categoria[]> GetAllCategoriasAsync()
        {
            return base.Channel.GetAllCategoriasAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Pedido> GetPedidoAsync(int ID)
        {
            return base.Channel.GetPedidoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PedidoItens[]> GetPedidoItensAsync(int ID)
        {
            return base.Channel.GetPedidoItensAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Pedido> GetRegistroInicialPedidoAsync()
        {
            return base.Channel.GetRegistroInicialPedidoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PedidoComDados> GetPedidoComDadosAsync(int ID)
        {
            return base.Channel.GetPedidoComDadosAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroPedidoAsync()
        {
            return base.Channel.GetProximoRegistroPedidoAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroPedidoAsync(int ID)
        {
            return base.Channel.AvancarRegistroPedidoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroPedidoAsync(int ID)
        {
            return base.Channel.VoltarRegistroPedidoAsync(ID);
        }
        
        public System.Threading.Tasks.Task salvarItensPedidoAsync(ServiceReference1.PedidoItens item)
        {
            return base.Channel.salvarItensPedidoAsync(item);
        }
        
        public System.Threading.Tasks.Task excluirItemPedidoAsync(int ID)
        {
            return base.Channel.excluirItemPedidoAsync(ID);
        }
        
        public System.Threading.Tasks.Task excluirItensPedidoAsync(int ID)
        {
            return base.Channel.excluirItensPedidoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<double> VerificarValorPedidoAsync(int ID)
        {
            return base.Channel.VerificarValorPedidoAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> FinalizarPedidoAsync(ServiceReference1.Pedido pedido)
        {
            return base.Channel.FinalizarPedidoAsync(pedido);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Entrada> GetEntradaAsync(int ID)
        {
            return base.Channel.GetEntradaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EntradaItens[]> GetEntradaItensAsync(int ID)
        {
            return base.Channel.GetEntradaItensAsync(ID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Entrada> GetRegistroInicialEntradaAsync()
        {
            return base.Channel.GetRegistroInicialEntradaAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EntradaComDados> GetEntradaComDadosAsync(int ID)
        {
            return base.Channel.GetEntradaComDadosAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> GetProximoRegistroEntradaAsync()
        {
            return base.Channel.GetProximoRegistroEntradaAsync();
        }
        
        public System.Threading.Tasks.Task<int> AvancarRegistroEntradaAsync(int ID)
        {
            return base.Channel.AvancarRegistroEntradaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> VoltarRegistroEntradaAsync(int ID)
        {
            return base.Channel.VoltarRegistroEntradaAsync(ID);
        }
        
        public System.Threading.Tasks.Task salvarItensEntradaAsync(ServiceReference1.EntradaItens item)
        {
            return base.Channel.salvarItensEntradaAsync(item);
        }
        
        public System.Threading.Tasks.Task excluirItemEntradaAsync(int ID)
        {
            return base.Channel.excluirItemEntradaAsync(ID);
        }
        
        public System.Threading.Tasks.Task excluirItensEntradaAsync(int ID)
        {
            return base.Channel.excluirItensEntradaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<double> VerificarValorEntradaAsync(int ID)
        {
            return base.Channel.VerificarValorEntradaAsync(ID);
        }
        
        public System.Threading.Tasks.Task<int> FinalizarEntradaAsync(ServiceReference1.Entrada entrada)
        {
            return base.Channel.FinalizarEntradaAsync(entrada);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListaPedido[]> GetListaPedidosAsync(string tipoPesquisa, string pesquisa)
        {
            return base.Channel.GetListaPedidosAsync(tipoPesquisa, pesquisa);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListaCliente[]> GetListaClientesAsync(string tipoPesquisa, string pesquisa, bool inativo, string tipoCliente)
        {
            return base.Channel.GetListaClientesAsync(tipoPesquisa, pesquisa, inativo, tipoCliente);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FormaPGTO[]> GetListaFormaPGTOAsync(string tipoPesquisa, string pesquisa, bool inativo)
        {
            return base.Channel.GetListaFormaPGTOAsync(tipoPesquisa, pesquisa, inativo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListaProduto[]> GetListaProdutosAsync(string tipoPesquisa, string pesquisa, bool inativo)
        {
            return base.Channel.GetListaProdutosAsync(tipoPesquisa, pesquisa, inativo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Categoria[]> GetListaCategoriasAsync(string tipoPesquisa, string pesquisa, bool inativo)
        {
            return base.Channel.GetListaCategoriasAsync(tipoPesquisa, pesquisa, inativo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Operador[]> GetListaOperadorAsync(string tipoPesquisa, string pesquisa, bool inativo)
        {
            return base.Channel.GetListaOperadorAsync(tipoPesquisa, pesquisa, inativo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListaEntrada[]> GetListaEntradasAsync(string tipoPesquisa, string pesquisa)
        {
            return base.Channel.GetListaEntradasAsync(tipoPesquisa, pesquisa);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PedidoComDados[]> GetRelatorioPedidoAsync(string dtInicio, string dtFinal, string cliente, string PGTO)
        {
            return base.Channel.GetRelatorioPedidoAsync(dtInicio, dtFinal, cliente, PGTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
